<!DOCTYPE html>
<html>
<title> Working with Online Forms </title>
<body>
■ nlapiAddDays(d, days)
■ nlapiAddMonths(d, months)
■ nlapiCancelLineItem(type)
■ nlapiDateToString(d, format)
■ nlapiDisableField(fldnam, val)
■ nlapiDisableLineItemField(type, fldnam, val)
■ nlapiEncrypt(s, algorithm, key)
■ nlapiEscapeXML(text)
■ nlapiFormatCurrency(str)
■ nlapiGetCurrentLineItemIndex(type)
■ nlapiGetCurrentLineItemText(type, fldnam)
■ nlapiGetCurrentLineItemValue(type, fldnam)
■ nlapiGetFieldText(fldnam)
■ nlapiGetLineItemText(type, fldnam, linenum)
■ nlapiIsLineItemChanged(type)
■ nlapiRefreshLineItems(type)
■ nlapiRemoveLineItemOption(type, fldnam, value)
■ nlapiRemoveSelectOption(fldnam, value)
■ nlapiSelectLineItem(type, linenum)
■ nlapiSelectNewLineItem(type)
■ nlapiGetLineItemCount(type)
■ nlapiGetFieldValue(fldnam)
■ nlapiSetFieldValue(fldnam, value, firefieldchanged, synchronous)
■ nlapiGetLineItemValue(type, fldnam, linenum)
■ nlapiSelectNode(node, xpath)
■ nlapiSelectNodes(node, xpath)
■ nlapiSelectValue(node, xpath)
■ nlapiSelectValues(node, path)
■ nlapiStringToDate(str, format) 
■ nlapiStringToXML(text)
■ nlapiXMLToString(xml)
■ nlapiSetLineItemValue(type, fldnam, linenum, value)
■ nlapiInsertLineItem(type, line)
■ nlapiRemoveLineItem(type, line) 
■ nlapiGetRecordType()
■ nlapiGetRecordId()
■ nlapiGetRole()
■ nlapiGetUser()
</body>
</html>